-- +goose Up
-- +goose StatementBegin
CREATE TABLE "user" (
                        "id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    -- Логин пользователя
                        "login" TEXT NOT NULL,
    -- Пароль с солью
                        "password" TEXT NOT NULL,
                        "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
                        "modified_at" TIMESTAMP,
    -- Флаг активности
                        "active" BOOLEAN NOT NULL DEFAULT True,
                        PRIMARY KEY("id")
);

CREATE UNIQUE INDEX "user_login_active_udx"
    ON "user" ("login", "active");

CREATE TABLE "user-balance" (
                                "id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                "user_id" BIGINT NOT NULL UNIQUE,
                                "balance" NUMERIC NOT NULL DEFAULT 0,
                                "withdrawals_sum" NUMERIC NOT NULL DEFAULT 0,
                                PRIMARY KEY("id")
);

CREATE TABLE "order" (
                         "id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                         "number" TEXT NOT NULL UNIQUE,
                         "user_id" BIGINT NOT NULL,
                         "status" TEXT NOT NULL DEFAULT 'NEW',
                         "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
                         "modified_at" TIMESTAMP,
                         PRIMARY KEY("id")
);

CREATE INDEX "order_user_id_idx"
    ON "order" ("user_id");

CREATE TABLE "accrual" (
                           "id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                           "amount" NUMERIC NOT NULL,
                           "user_id" BIGINT NOT NULL,
                           "order_id" BIGINT NOT NULL UNIQUE,
                           "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
                           PRIMARY KEY("id")
);
CREATE INDEX "accrual_user_id_idx"
    ON "accrual" ("user_id");

CREATE TABLE "withdrawal" (
                              "id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                              "amount" NUMERIC NOT NULL,
                              "user_id" BIGINT NOT NULL,
                              "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    -- Номер гипотетического заказа, в рамках которого происходит списание.
    -- Вне скоупа таблицы заказов, поэтому отдельным полем
                              "withdrawal_order_number" TEXT NOT NULL UNIQUE,
                              PRIMARY KEY("id")
);
CREATE INDEX "withdrawal_user_id_idx"
    ON "withdrawal" ("user_id");

ALTER TABLE "withdrawal"
    ADD FOREIGN KEY("user_id") REFERENCES "user"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "user-balance"
    ADD FOREIGN KEY("user_id") REFERENCES "user"("id")
        ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "accrual"
    ADD FOREIGN KEY("user_id") REFERENCES "user"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "order"
    ADD FOREIGN KEY("user_id") REFERENCES "user"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "accrual"
    ADD FOREIGN KEY("order_id") REFERENCES "order"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP INDEX "user_login_active_udx";
DROP INDEX "order_user_id_idx";
DROP INDEX "accrual_user_id_idx";
DROP INDEX "withdrawal_user_id_idx";


DROP TABLE "accrual";
DROP TABLE "order";
DROP TABLE "withdrawal";
DROP TABLE "user-balance";
DROP TABLE "user";
-- +goose StatementEnd
